CREATE DATABASE IF NOT EXISTS cadastro_escola;
USE cadastro_escola;

CREATE TABLE IF NOT EXISTS cliente (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    nome_social VARCHAR(100),
    cpf VARCHAR(14),
    genero VARCHAR(50),
    afrodescendente BOOLEAN,
    escolaridade_publica BOOLEAN,
    data_nascimento VARCHAR(10),
    local_nascimento VARCHAR(100),
    nacionalidade VARCHAR(80),
    pais_origem VARCHAR(80),
    filiacao1 VARCHAR(100),
    filiacao2 VARCHAR(100),
    responsavel_legal VARCHAR(100),
    grau_parentesco VARCHAR(50),
    habilitacao VARCHAR(100),
    periodo VARCHAR(50),
    serie_modulo VARCHAR(50),
    rua_avenida VARCHAR(150),
    bairro VARCHAR(100),
    complemento VARCHAR(100),
    apto VARCHAR(20),
    bloco VARCHAR(20),
    cep VARCHAR(10),
    cidade VARCHAR(100),
    telefone VARCHAR(20),
    celular VARCHAR(20),
    email VARCHAR(150),
    estuda_atualmente_etec BOOLEAN,
    estuda_outra_etec BOOLEAN,
    ja_estudou_etec BOOLEAN,
    concluiu_ensino_medio BOOLEAN,
    escola_ensino_medio VARCHAR(150)
);
